export class HistorialKPI {

    CLAVEPROCESOEVALUACIONKPI: string;
    NOMBREPROCESOEVALUACIONKPI: string;
    FECHAINICIOPROCESOGENERAL: string;
    FECHAFINPROCESOGENERAL: string;
    DESCRIPCIONPROCESOKPIVIGENTE: string;
    IDPROCESOVIGENTE: string;

}