export class MisEdd {   
    NOMBREPROCESOEVALUACION: string;
    FECHAINICIOPROCESOEVALUACION: Date;
    FECHAFINPROCESOEVALUACION: Date;
    NOMBREUNIDADADMINISTRATIVA: string;
    NOMBREPUESTO: string;
    CALIFICACION: string;
    CONSTANCIA: string;
    IDPROCESOVIGENTE:string;
}