export class ProcesoKPIVigente {
    CLAVEPROCESOEVALUACIONKPI: string;
    NOMBREPROCESOEVALUACIONKPI: string;
    FECHAINICIOPROCESOGENERAL: string;
    FECHAFINPROCESOGENERAL: string;
    DESCRIPCIONPROCESOKPIVIGENTE: string;
    IDPROCESOVIGENTE:string;
}