package mx.gob.edomex.microservicios.servicios.sei.bus.models;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonProperty;

@Entity
public class DetalleEDD implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	private String IDEVALUACIONVIGENTE;
	private String NOMBREEVALUACIONVIGENTE;
	private String IDUNIDADADMINISTRATIVA;
	private String NOMBREUNIDADADMINISTRATIVA;
	private String TOTALSERVIDORESPUBLICOS;
	private String TOTALSERVIDORESPUBLICOSEVALUADOS;
	private String TOTALSERVIDORESPUBLICOSFALTANTES;
	private String PORCENTAJEAVANZE;

	@JsonProperty("IDEVALUACIONVIGENTE")
	public String getIDEVALUACIONVIGENTE() {
		return IDEVALUACIONVIGENTE;
	}

	public void setIDEVALUACIONVIGENTE(String iDEVALUACIONVIGENTE) {
		IDEVALUACIONVIGENTE = iDEVALUACIONVIGENTE;
	}

	@JsonProperty("NOMBREEVALUACIONVIGENTE")
	public String getNOMBREEVALUACIONVIGENTE() {
		return NOMBREEVALUACIONVIGENTE;
	}

	public void setNOMBREEVALUACIONVIGENTE(String nOMBREEVALUACIONVIGENTE) {
		NOMBREEVALUACIONVIGENTE = nOMBREEVALUACIONVIGENTE;
	}

	@JsonProperty("IDUNIDADADMINISTRATIVA")
	public String getIDUNIDADADMINISTRATIVA() {
		return IDUNIDADADMINISTRATIVA;
	}

	public void setIDUNIDADADMINISTRATIVA(String iDUNIDADADMINISTRATIVA) {
		IDUNIDADADMINISTRATIVA = iDUNIDADADMINISTRATIVA;
	}

	@JsonProperty("NOMBREUNIDADADMINISTRATIVA")
	public String getNOMBREUNIDADADMINISTRATIVA() {
		return NOMBREUNIDADADMINISTRATIVA;
	}

	public void setNOMBREUNIDADADMINISTRATIVA(String nOMBREUNIDADADMINISTRATIVA) {
		NOMBREUNIDADADMINISTRATIVA = nOMBREUNIDADADMINISTRATIVA;
	}

	@JsonProperty("TOTALSERVIDORESPUBLICOS")
	public String getTOTALSERVIDORESPUBLICOS() {
		return TOTALSERVIDORESPUBLICOS;
	}

	public void setTOTALSERVIDORESPUBLICOS(String tOTALSERVIDORESPUBLICOS) {
		TOTALSERVIDORESPUBLICOS = tOTALSERVIDORESPUBLICOS;
	}

	@JsonProperty("TOTALSERVIDORESPUBLICOSEVALUADOS")
	public String getTOTALSERVIDORESPUBLICOSEVALUADOS() {
		return TOTALSERVIDORESPUBLICOSEVALUADOS;
	}

	public void setTOTALSERVIDORESPUBLICOSEVALUADOS(String tOTALSERVIDORESPUBLICOSEVALUADOS) {
		TOTALSERVIDORESPUBLICOSEVALUADOS = tOTALSERVIDORESPUBLICOSEVALUADOS;
	}

	@JsonProperty("TOTALSERVIDORESPUBLICOSFALTANTES")
	public String getTOTALSERVIDORESPUBLICOSFALTANTES() {
		return TOTALSERVIDORESPUBLICOSFALTANTES;
	}

	public void setTOTALSERVIDORESPUBLICOSFALTANTES(String tOTALSERVIDORESPUBLICOSFALTANTES) {
		TOTALSERVIDORESPUBLICOSFALTANTES = tOTALSERVIDORESPUBLICOSFALTANTES;
	}

	@JsonProperty("PORCENTAJEAVANZE")
	public String getPORCENTAJEAVANZE() {
		return PORCENTAJEAVANZE;
	}

	public void setPORCENTAJEAVANZE(String pORCENTAJEAVANZE) {
		PORCENTAJEAVANZE = pORCENTAJEAVANZE;
	}

}
