package mx.gob.edomex.microservicios.servicios.sei.bus.models;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonProperty;

@Entity
public class ProcesoVigente implements Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	private String CLAVEPROCESOEVALUACION;
	private String NOMBREPROCESOEVALUACION;
	private String FECHAINICIOPROCESOGENERAL;
	private String FECHAFINPROCESOGENERAL;
	private String FECHAINICIOCAPTURADEMERITOS;
	private String FECHAFINCAPTURADEMERITOS;
	private String DESCRIPCIONPROCESOVIGENTE;
	private String IDPROCESOVIGENTE;

	@JsonProperty("CLAVEPROCESOEVALUACION")
	public String getCLAVEPROCESOEVALUACION() {
		return CLAVEPROCESOEVALUACION;
	}

	public void setCLAVEPROCESOEVALUACION(String cLAVEPROCESOEVALUACION) {
		CLAVEPROCESOEVALUACION = cLAVEPROCESOEVALUACION;
	}

	@JsonProperty("NOMBREPROCESOEVALUACION")
	public String getNOMBREPROCESOEVALUACION() {
		return NOMBREPROCESOEVALUACION;
	}

	public void setNOMBREPROCESOEVALUACION(String nOMBREPROCESOEVALUACION) {
		NOMBREPROCESOEVALUACION = nOMBREPROCESOEVALUACION;
	}

	@JsonProperty("FECHAINICIOPROCESOGENERAL")
	public String getFECHAINICIOPROCESOGENERAL() {
		return FECHAINICIOPROCESOGENERAL;
	}

	public void setFECHAINICIOPROCESOGENERAL(String fECHAINICIOPROCESOGENERAL) {
		FECHAINICIOPROCESOGENERAL = fECHAINICIOPROCESOGENERAL;
	}

	@JsonProperty("FECHAFINPROCESOGENERAL")
	public String getFECHAFINPROCESOGENERAL() {
		return FECHAFINPROCESOGENERAL;
	}

	public void setFECHAFINPROCESOGENERAL(String fECHAFINPROCESOGENERAL) {
		FECHAFINPROCESOGENERAL = fECHAFINPROCESOGENERAL;
	}

	@JsonProperty("FECHAINICIOCAPTURADEMERITOS")
	public String getFECHAINICIOCAPTURADEMERITOS() {
		return FECHAINICIOCAPTURADEMERITOS;
	}

	public void setFECHAINICIOCAPTURADEMERITOS(String fECHAINICIOCAPTURADEMERITOS) {
		FECHAINICIOCAPTURADEMERITOS = fECHAINICIOCAPTURADEMERITOS;
	}

	@JsonProperty("FECHAFINCAPTURADEMERITOS")
	public String getFECHAFINCAPTURADEMERITOS() {
		return FECHAFINCAPTURADEMERITOS;
	}

	public void setFECHAFINCAPTURADEMERITOS(String fECHAFINCAPTURADEMERITOS) {
		FECHAFINCAPTURADEMERITOS = fECHAFINCAPTURADEMERITOS;
	}

	@JsonProperty("DESCRIPCIONPROCESOVIGENTE")
	public String getDESCRIPCIONPROCESOVIGENTE() {
		return DESCRIPCIONPROCESOVIGENTE;
	}

	public void setDESCRIPCIONPROCESOVIGENTE(String dESCRIPCIONPROCESOVIGENTE) {
		DESCRIPCIONPROCESOVIGENTE = dESCRIPCIONPROCESOVIGENTE;
	}

	@JsonProperty("IDPROCESOVIGENTE")
	public String getIDPROCESOVIGENTE() {
		return IDPROCESOVIGENTE;
	}

	public void setIDPROCESOVIGENTE(String iDPROCESOVIGENTE) {
		IDPROCESOVIGENTE = iDPROCESOVIGENTE;
	}

}
