package mx.gob.edomex.microservicios.servicios.sei.bus.models;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonProperty;

@Entity
public class ProcesoKPIVigente implements Serializable {
	private static final long serialVersionUID = 1L;
	@Id
	private String CLAVEPROCESOEVALUACIONKPI;
	private String NOMBREPROCESOEVALUACIONKPI;
	private String FECHAINICIOPROCESOGENERAL;
	private String FECHAFINPROCESOGENERAL;
	private String DESCRIPCIONPROCESOKPIVIGENTE;
	private String IDPROCESOVIGE;

	@JsonProperty("CLAVEPROCESOEVALUACIONKPI")
	public String getCLAVEPROCESOEVALUACIONKPI() {
		return CLAVEPROCESOEVALUACIONKPI;
	}

	public void setCLAVEPROCESOEVALUACIONKPI(String cLAVEPROCESOEVALUACIONKPI) {
		CLAVEPROCESOEVALUACIONKPI = cLAVEPROCESOEVALUACIONKPI;
	}

	@JsonProperty("NOMBREPROCESOEVALUACIONKPI")
	public String getNOMBREPROCESOEVALUACIONKPI() {
		return NOMBREPROCESOEVALUACIONKPI;
	}

	public void setNOMBREPROCESOEVALUACIONKPI(String nOMBREPROCESOEVALUACIONKPI) {
		NOMBREPROCESOEVALUACIONKPI = nOMBREPROCESOEVALUACIONKPI;
	}

	@JsonProperty("FECHAINICIOPROCESOGENERAL")
	public String getFECHAINICIOPROCESOGENERAL() {
		return FECHAINICIOPROCESOGENERAL;
	}

	public void setFECHAINICIOPROCESOGENERAL(String fECHAINICIOPROCESOGENERAL) {
		FECHAINICIOPROCESOGENERAL = fECHAINICIOPROCESOGENERAL;
	}

	@JsonProperty("FECHAFINPROCESOGENERAL")
	public String getFECHAFINPROCESOGENERAL() {
		return FECHAFINPROCESOGENERAL;
	}

	public void setFECHAFINPROCESOGENERAL(String fECHAFINPROCESOGENERAL) {
		FECHAFINPROCESOGENERAL = fECHAFINPROCESOGENERAL;
	}

	@JsonProperty("DESCRIPCIONPROCESOKPIVIGENTE")
	public String getDESCRIPCIONPROCESOKPIVIGENTE() {
		return DESCRIPCIONPROCESOKPIVIGENTE;
	}

	public void setDESCRIPCIONPROCESOKPIVIGENTE(String dESCRIPCIONPROCESOKPIVIGENTE) {
		DESCRIPCIONPROCESOKPIVIGENTE = dESCRIPCIONPROCESOKPIVIGENTE;
	}

	@JsonProperty("IDPROCESOVIGE")
	public String getIDPROCESOVIGE() {
		return IDPROCESOVIGE;
	}

	public void setIDPROCESOVIGE(String iDPROCESOVIGE) {
		IDPROCESOVIGE = iDPROCESOVIGE;
	}

}
